language: python
python:
    - 2.7
    - 3.4
    - 3.5
    - 3.6
before_install:
    - sudo apt-get -y update
install:
    - pip install codecov --progress-bar off
    - pip install -r requirements.txt --progress-bar off
script:
    - nosetests
after_success:
    - codecov