language: python
python:
    - 2.7
    - 3.4
    - 3.5
    - 3.6
before_install:
    - sudo apt-get update
install:
    - sudo apt-get -y install r-base
    - pip install codecov
    - pip install -r requirements.txt
script:
    - nosetests
after_success:
    - codecov