language: python
python:
    - 2.7
    - 3.4
    - 3.5
    - 3.6
before_install:
    - sudo apt-get -y update
install:
    - pip install codecov --quiet 
    - pip install -r requirements.txt --quiet 
script:
    - nosetests
after_success:
    - codecov