language: python
python:
    - 2.7
    - 3.5
    - 3.6
before_install:
    - sudo apt-get -y update
install:
    - pip --no-cache-dir install . 
    - pip --no-cache-dir install nose --quiet
script:
    - make test
