{% set version = "0.4.2" %}


package:
  name: mimsi
  version: {{ version }}

source:
  url: "https://github.com/mskcc/mimsi/archive/refs/heads/feature/add-conda-support.zip"


build:
  number: 0
  python: {{ python }}
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv "

requirements:
  host:
    - python
    - setuptools
    - pip

  run:
    - python
    - future
    - nose >=1.3.7
    - pytorch ==1.4.0
    - torchvision ==0.5.0
    - numpy ==1.14.6 # [py==35]
    - numpy # [py>=36]
    - numpy # [py==27]
    - pandas ==0.24.2 # [py==27]
    - pandas # [py>=35]
    - pysam
    - scikit-learn # [py>=35]
    - scikit-learn >=0.20.0 # [py==27]
  


test:
  commands:
    - evaluate_sample --version
    - analyze --version
    - create_data --version
    - mi_msi_train_test --version